import { AGENTS } from "./agents";
import type { BrowserAction, TestCase } from "./db";

const str = (s: string | undefined): string => JSON.stringify(s ?? "");
const escapeRegExp = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function toCode({ action, selector, value }: BrowserAction): string {
  const loc = `page.locator(${str(selector)})`;
  switch (action) {
    case "goto":
      return `await page.goto(${str(value)});`;
    case "click":
      return `await ${loc}.click();`;
    case "dblclick":
      return `await ${loc}.dblclick();`;
    case "back":
      return "await page.goBack();";
    case "reload":
      return "await page.reload();";
    case "fill":
      return `await ${loc}.fill(${str(value)});`;
    case "press":
      return selector ? `await ${loc}.press(${str(value)});` : `await page.keyboard.press(${str(value)});`;
    case "select":
      return `await ${loc}.selectOption(${str(value)});`;
    case "hover":
      return `await ${loc}.hover();`;
    case "expect_visible":
      return `await expect(${loc}).toBeVisible();`;
    case "expect_text":
      return selector
        ? `await expect(${loc}.filter({ hasText: ${str(value)} }).first()).toBeVisible();`
        : `await expect(page.getByText(${str(value)}).first()).toBeVisible();`;
    case "expect_hidden":
      return selector
        ? `await expect(${loc}.first()).toBeHidden();`
        : `await expect(page.getByText(${str(value)}).first()).toBeHidden();`;
    case "expect_value":
      return `await expect(${loc}).toHaveValue(${str(value)});`;
    case "expect_url":
      return `await expect(page).toHaveURL(new RegExp(${str(escapeRegExp(value ?? ""))}));`;
  }
}

/**
 * Text placed inside a `//` comment. Every JavaScript line terminator (\r, \n, U+2028, U+2029) ends a comment,
 * so one left in a URL or in model-written text would turn the rest of the line into live code in the
 * customer's suite. Code values go through str() (JSON), which is safe inside string literals.
 */
// CR, LF, U+2028 and U+2029, built from char codes so this source file stays plain ASCII.
const LINE_BREAKS = new RegExp(`[${String.fromCharCode(13, 10, 0x2028, 0x2029)}]+`, "g");
const comment = (text: string): string => text.replace(LINE_BREAKS, " ");

function toTest(c: TestCase, indent: string): string {
  const note =
    c.status === "failed"
      ? [`// BUG (${c.severity ?? "minor"}): ${comment(c.actual ?? "")}`, "// Fails until the bug is fixed."]
      : [];
  const body = [...note, `// Expected: ${comment(c.expected)}`, ...c.actions.map(toCode)];
  return [
    `${indent}test(${str(`#${c.seq} ${c.title}`)}, async ({ page }) => {`,
    ...body.map((line) => `${indent}  ${line}`),
    `${indent}});`,
  ].join("\n");
}

const MOBILE_USE =
  'test.use({ viewport: devices["Pixel 7"].viewport, userAgent: devices["Pixel 7"].userAgent, isMobile: true, hasTouch: true });';

/** Turns the browser actions the tester performed into a runnable Playwright suite, grouped by agent. */
export function buildSpec(siteUrl: string, cases: TestCase[]): string {
  // Tests that only open a page (the automated page-load, accessibility and performance checks) prove
  // nothing as Playwright code, so they stay in the report but out of the suite.
  const executed = cases.filter((c) => (c.status === "passed" || c.status === "failed") && c.actions.length > 1);
  const groups = AGENTS.map((agent) => {
    const own = executed.filter((c) => c.agent === agent.id);
    if (own.length === 0) return [];
    const desktop = own.filter((c) => c.viewport === "desktop");
    const mobile = own.filter((c) => c.viewport === "mobile");
    return [
      `test.describe(${str(`${agent.testType} · ${agent.name}`)}, () => {`,
      ...desktop.map((c) => toTest(c, "  ") + "\n"),
      ...(mobile.length
        ? ['  test.describe("mobile", () => {', `    ${MOBILE_USE}`, "", ...mobile.map((c) => toTest(c, "    ") + "\n"), "  });"]
        : []),
      "});",
      "",
    ];
  });

  return [
    `// QA suite for ${comment(siteUrl)}, generated by TestShift.`,
    "// Run with: npx playwright test",
    'import { test, expect, devices } from "@playwright/test";',
    "",
    ...groups.flat(),
  ].join("\n");
}
