import { AGENTS } from "./agents";
import type { BrowserAction, TestCase } from "./db";

const str = (s: string | undefined): string => JSON.stringify(s ?? "");
const escapeRegExp = (s: string): string => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

function toCode({ action, selector, value }: BrowserAction): string {
  const loc = `page.locator(${str(selector)})`;
  switch (action) {
    case "goto":
      return `await page.goto(${str(value)});`;
    case "click":
      return `await ${loc}.click();`;
    case "dblclick":
      return `await ${loc}.dblclick();`;
    case "back":
      return "await page.goBack();";
    case "reload":
      return "await page.reload();";
    case "fill":
      return `await ${loc}.fill(${str(value)});`;
    case "press":
      return selector ? `await ${loc}.press(${str(value)});` : `await page.keyboard.press(${str(value)});`;
    case "select":
      return `await ${loc}.selectOption(${str(value)});`;
    case "hover":
      return `await ${loc}.hover();`;
    case "expect_visible":
      return `await expect(${loc}).toBeVisible();`;
    case "expect_text":
      return selector
        ? `await expect(${loc}.filter({ hasText: ${str(value)} }).first()).toBeVisible();`
        : `await expect(page.getByText(${str(value)}).first()).toBeVisible();`;
    case "expect_url":
      return `await expect(page).toHaveURL(new RegExp(${str(escapeRegExp(value ?? ""))}));`;
  }
}

function toTest(c: TestCase, indent: string): string {
  const note =
    c.status === "failed"
      ? [`// BUG (${c.severity ?? "minor"}): ${c.actual ?? ""}`, "// Fails until the bug is fixed."]
      : [];
  const body = [...note, `// Expected: ${c.expected}`, ...c.actions.map(toCode)];
  return [
    `${indent}test(${str(`#${c.seq} ${c.title}`)}, async ({ page }) => {`,
    ...body.map((line) => `${indent}  ${line.replace(/\n/g, " ")}`),
    `${indent}});`,
  ].join("\n");
}

const MOBILE_USE =
  'test.use({ viewport: devices["Pixel 7"].viewport, userAgent: devices["Pixel 7"].userAgent, isMobile: true, hasTouch: true });';

/** Turns the browser actions the tester performed into a runnable Playwright suite, grouped by agent. */
export function buildSpec(siteUrl: string, cases: TestCase[]): string {
  const executed = cases.filter((c) => (c.status === "passed" || c.status === "failed") && c.actions.length > 0);
  const groups = AGENTS.map((agent) => {
    const own = executed.filter((c) => c.agent === agent.id);
    if (own.length === 0) return [];
    const desktop = own.filter((c) => c.viewport === "desktop");
    const mobile = own.filter((c) => c.viewport === "mobile");
    return [
      `test.describe(${str(`${agent.testType} · ${agent.name}`)}, () => {`,
      ...desktop.map((c) => toTest(c, "  ") + "\n"),
      ...(mobile.length
        ? ['  test.describe("mobile", () => {', `    ${MOBILE_USE}`, "", ...mobile.map((c) => toTest(c, "    ") + "\n"), "  });"]
        : []),
      "});",
      "",
    ];
  });

  return [
    `// QA suite for ${siteUrl}, generated by TestShift.`,
    "// Run with: npx playwright test",
    'import { test, expect, devices } from "@playwright/test";',
    "",
    ...groups.flat(),
  ].join("\n");
}
